name: Invoke Lambda
on:
  push:
    branches:
      - main
jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Invoke Lambda
      run: aws lambda invoke --function-name rj-function --cli-binary-format raw-in-base64-out --payload '{"updated_files:" "'$(git diff-tree --no-commit-id --name-only -r HEAD --no-renames)'"}' output.json
