name: Lambda Update

on:
  push:
    branches:
      - main
jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Invoke Lambda
      uses: aws-actions/aws-cli@v1
      with:
        args:lambda invoke --function-name rj-function --payload "{\"updated_files\": \"$(git diff-tree --no-commit-id --name-only -r HEAD)\"}" output.json

