name: Lambda Update

on:
  push:
    branches:
      - main
jobs:
  invoke-lambda:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    - name: Invoke Lambda
      uses: aws-actions/aws-cli@v1
      with:
        args: lambda invoke --function-name my-function --payload '{"updated_files": "'"$(git diff-tree --no-commit-id --name-only -r HEAD)"'"}' output.json
    

    
